version: "3.9"

services:
  # ============================================================
  # Development dengan Air (hot reload)
  # ============================================================
  gateway-dev:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - gateway-dev-data:/app/data
    environment:
      - TZ=Asia/Jakarta
      - GOFLAGS=-mod=mod
    command: ["air", "-c", ".air.toml"]

volumes:
  gateway-dev-data:
